### ISSUE TITLE
ISO8601 datetime

### ISSUE THREAD

**Issue by juancarlospaco** [diegogub/jdec#1]
Segun el standard ISO-8601 el char separador que por defecto es `"T"` puede ser cualquier otro char,
inclusive espacio o unicode o emoji, y seguiria siendo un ISO-8601 valido, es comun usar `" "` en lugar de la `"T"`,
pienso que la libreria me deberia dejar pasar 1 char como argumento para usar ahi.

**Comment by diegogub** [comment]
@juancarlospaco si, talvez se podria hacer una constante generada. Siendo default T o el " "

**Comment by diegogub** [comment]
@juancarlospaco capaz algo mas generico seria agregar la opcion para agregar cualquier formato de tiempo que uno quiera.. no?

**Comment by diegogub** [comment]
Added, dateFormat  to support custom dateTime formats.

**Comment by juancarlospaco** [comment]
Con que soporte el ISO me conformo jeje, pero eso esta muy bien tambien. :+1:
